name: Release

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use the Node.js version you need
          registry-url: 'https://registry.npmjs.org/'  # Set the npm registry

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test  # Adjust this if your test command is different

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}          # NPM token for publishing
        run: npx semantic-release
